pipeline:
  identifier: Build_navneetk98_todo_app_example_1736105802412
  name: Build todo-app-example
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1736104493429
        repoName: navneetk98/todo-app-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - parallel:
                  - step:
                      identifier: test
                      name: test
                      spec:
                        command: npm run test
                      timeout: ""
                      type: Run
                  - step:
                      type: BuildAndPushDockerRegistry
                      name: BuildAndPushDockerRegistry_2
                      identifier: BuildAndPushDockerRegistry_2
                      spec:
                        connectorRef: docker_hub
                        repo: iamnavneet/navneet-todo-test
                        tags:
                          - docker_build_2
                        caching: true
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: <+input>
                    repo: navneet-todo-test
                    tags:
                      - latest
                    caching: true
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        delegateSelectors:
          - kubernetes-delegate-laptop
    - stage:
        name: dpeloy
        identifier: dpeloy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: testtodoservice
          environment:
            environmentRef: qa
            deployToAll: false
            infrastructureDefinitions:
              - identifier: mac_local_infra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
